# Any commit to master branch re-builds images, re-runs tests, and pushes SHA tags to DockerHub
name: Build and Push
on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'Makefile'
      - 'environment-condalock.yml'
      - 'update_lockfile.sh'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'Makefile'
      - 'environment-condalock.yml'
      - 'update_lockfile.sh'

env:
  QUAYIO_ORG: mardatade
  IMAGE_NAME_PREFIX: oscm2024
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [default, ch1pyr423, springschool_py, springschool_r]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Job Environment Variables
      run: |
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

    # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
    - name: Free up disk space
      run: |
        df -h
        docker image ls
        sudo apt clean
        sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
        df -h

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Quay.io
      if: ${{ startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') }}
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Build and push main
      if: ${{ startsWith(github.ref, 'refs/heads/main') }}
      uses: docker/build-push-action@v3
      with:
        context: ${{ matrix.IMAGE }}
        push: true
        tags: |
          quay.io/${{env.QUAYIO_ORG}}/${{env.IMAGE_NAME_PREFIX}}_${{ matrix.IMAGE }}:main
          quay.io/${{env.QUAYIO_ORG}}/${{env.IMAGE_NAME_PREFIX}}_${{ matrix.IMAGE }}:${{env.DOCKER_TAG}}

    - name: Build and push tag
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: docker/build-push-action@v3
      with:
        context: ${{ matrix.IMAGE }}
        push: true
        tags: |
          quay.io/${{env.QUAYIO_ORG}}/${{env.IMAGE_NAME_PREFIX}}_${{ matrix.IMAGE }}:${{github.ref_name}}
          quay.io/${{env.QUAYIO_ORG}}/${{env.IMAGE_NAME_PREFIX}}_${{ matrix.IMAGE }}:${{env.DOCKER_TAG}}
          quay.io/${{env.QUAYIO_ORG}}/${{env.IMAGE_NAME_PREFIX}}_${{ matrix.IMAGE }}:latest

    - name: Make repo public
      if: ${{ startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') }}
      run: |
        curl -X POST https://quay.io//api/v1/repository/${{env.QUAYIO_ORG}}/${{env.IMAGE_NAME_PREFIX}}_${{ matrix.IMAGE }}/changevisibility \
        -H 'Authorization: Bearer ${{secrets.QUAY_API_TOKEN}}' \
        -H 'Content-Type: application/json' \
        -d '{"visibility": "public"}'

    - name: Inspect Image
      continue-on-error: true
      if: ${{ startsWith(github.ref, 'refs/heads/main') }}
      run: |
        docker run quay.io/${{env.QUAYIO_ORG}}/${{env.IMAGE_NAME_PREFIX}}_${{ matrix.IMAGE }}:main conda list
        docker images ls
