# Any commit to master branch re-builds images, re-runs tests, and pushes SHA tags to DockerHub
name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'Makefile'
      - 'environment-condalock.yml'
      - 'update_lockfile.sh'

env:
  QUAYIO_ORG: mardatade
  IMAGE_NAME_PREFIX: oscm2024
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [default, ]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Job Environment Variables
      run: |
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

    # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
    - name: Free up disk space
      run: |
        df -h
        docker image ls
        sudo apt clean
        sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
        df -h

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ matrix.IMAGE }}
        push: true
        tags: |
          quay.io/${{env.QUAYIO_ORG}}/${IMAGE_NAME_PREFIX}_${{ matrix.IMAGE }}:main
          quay.io/${{env.QUAYIO_ORG}}/${IMAGE_NAME_PREFIX}_${{ matrix.IMAGE }}:${{env.DOCKER_TAG}}

    - name: Inspect Image
      run: |
        docker run $quay.io/${{env.QUAYIO_ORG}}/${IMAGE_NAME_PREFIX}_${{ matrix.IMAGE }}:main conda list
        docker images ls

    - name: Test Image
      run: |
        docker run -u 1000 -w /srv/test -v $PWD:/srv/test quay.io/${{env.QUAYIO_ORG}}/${IMAGE_NAME_PREFIX}_${{ matrix.IMAGE }}:main ./run_tests.sh ${{ matrix.IMAGE }}